#!/usr/bin/env python2.7

import sys
import naoqi
from naoqi import ALProxy
import time
import almath
import rospy
import roslib
from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint
rospy.init_node('mover', anonymous=True)
ph = rospy.Publisher('/nao_dcm/Head_controller/command', JointTrajectory, queue_size = 100)
r = rospy.Rate(100)
jt = JointTrajectory()
jtp = JointTrajectoryPoint()
jtp.positions = [0,0]
jtp.velocities = []
jtp.accelerations = []
jtp.effort = []

def pub(p, jt)
	p.publish(jt)
	print jt

def head_shake()
	jt.joint_names = ['HeadPitch','HeadYaw']
	jtp.time_from_start = rospy.Duration(0.5)
	
	while x < 5:
		jtp.positions = [-0.7,1.6]
		jt.points.append(jtp)
		pub(ph, jt)
		jtp.positions = [-0.7,0.0]
		jt.points.append(jtp)
		pub(ph, jt)
		jtp.positions = [-0.7,-1.6]
		jt.points.append(jtp)
		pub(ph, jt)


def myhook():
  print "over!"

rospy.on_shutdown(myhook)

while not rospy.is_shutdown():
		
		
		head_shake()
		
		except KeyboardInterrupt:
			sys.exit()

		
		
	
