#!/usr/bin/env python2.7

import sys
import naoqi
from naoqi import ALProxy
import time
import almath
import rospy
import roslib
from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint


class Mover:
	def __init__(self):
		rospy.init_node('mover', anonymous=True)
		self.ph = rospy.Publisher('/nao_dcm/Head_controller/command', JointTrajectory, queue_size=100)
		self.pal = rospy.Publisher('/nao_dcm/LeftArm_controller/command', JointTrajectory, queue_size=100)
		self.par = rospy.Publisher('/nao_dcm/RightArm_controller/command', JointTrajectory, queue_size=100)
		self.r = rospy.Rate(100)
		self.jt = JointTrajectory()
		self.jtp = JointTrajectoryPoint()
		self.interval = 0.5
		self.headJ = ['HeadPitch', 'HeadYaw']
		self.LArmJ = ['LShoulderPitch', 'LShoulderRoll', 'LElbowYaw', 'LElbowRoll', 'LHand']
		self.LArmJ = ['RShoulderPitch', 'RShoulderRoll', 'RElbowYaw', 'RElbowRoll', 'RHand']

	def pub(self, p):
		p.publish(self.jt)

	def move(self, goal, p):
		self.move_setup()
		self.jtp.positions = goal
		self.jtp.time_from_start = rospy.Duration(self.interval)
		self.jt.points.append(self.jtp)
		self.pub(p)

	def move_setup(self):
		self.jt.points = []
		self.jtp.positions = []
		self.jtp.velocities = []
		self.jtp.accelerations = []
		self.jtp.effort = []
		self.jtp.time_from_start = rospy.Duration()

	def body_reset(self):
		self.move_setup()
		self.jt.joint_names = self.headJ
		goal = [0.0, 0.0]
		self.move(goal, self.ph)
		self.move_setup()
		self.jt.joint_names = self.LArmJ
		goal = [0.0, 0.0, 0.0 , 0.0]
		self.move(goal, self.ph)



	def head_nod(self, sad):
		self.jt.joint_names = ['HeadPitch', 'HeadYaw']
		p = self.ph
		if sad:
			self.interval = 0.4
			goal = [0.0, 0.0]
			self.move(goal, p)
			goal[0] += 0.6
			self.move(goal, p)
			goal[1] -= 0.6
			self.move(goal, p)
	
		else:
			self.interval = 0.5
			goal = [0.0, 0.0]
			self.move(goal, p)
			goal[0] += 1
			self.move(goal, p)
			goal[0] -= 1
			self.move(goal, p)

	def head_shake(self, sad):
		self.jt.joint_names = ['HeadPitch', 'HeadYaw']
		p = self.ph
		i = self.interval
		if sad:
			i = 0.5
			goal = [0.4, 1.0]
			self.move(goal, p)
			rospy.sleep(i)
			goal[1] -= 1
			self.move(goal, p)
			rospy.sleep(i)
			goal[1] -= 1
			self.move(goal, p)
			rospy.sleep(i)
			goal[1] += 1
			self.move(goal, p)
			rospy.sleep(i)

		else:
			i = 0.2
			goal = [0.0, 1.0]
			self.move(goal, p)
			rospy.sleep(i)
			goal[1] -= 1
			self.move(goal, p)
			rospy.sleep(i)
			goal[1] -= 1
			self.move(goal, p)
			rospy.sleep(i)
			goal[1] += 1
			self.move(goal, p)
			rospy.sleep(i)

def my_hook():
	print "shutting down"


rospy.on_shutdown(my_hook)

test = Mover()

while not rospy.is_shutdown():
	try:
		test.head_shake(False)
		#test.head_nod(True)

	except KeyboardInterrupt:
		sys.exit()
